FROM golang:1.19

WORKDIR /chaum_pedersen

COPY go.mod go.sum ./

RUN go mod download

COPY zkp_auth ./zkp_auth
COPY server ./server

RUN GOOS=linux go build -o ./server ./server/server.go

CMD ["./server/server"]