version: '3.8'

services:
  zkp_auth_server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "50051:50051"

  zkp_auth_client:
    build:
      context: .
      dockerfile: Dockerfile-client
