FROM golang:1.19

WORKDIR /chaum_pedersen

COPY go.mod go.sum ./

RUN go mod download

COPY zkp_auth ./zkp_auth
COPY client ./client

RUN GOOS=linux go build -o ./client ./client/client.go

CMD ["./client/client"]