FROM golang:1.19

WORKDIR /chaum_pedersen

COPY go.mod go.sum ./

RUN go mod download

COPY zkp_auth ./zkp_auth
COPY client ./client

RUN apt-get update && apt-get install -y netcat-openbsd coreutils

RUN GOOS=linux go build -o ./client ./client/client.go

CMD ["./client/wait-for-server.sh", "zkp_auth_server", "50051", "./client/client"]
